### ISSUE TITLE
Todo for 1.12.1

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#126]
### Comment:

- [ ] Revisit the licenses https://github.com/conda-forge/pytorch-cpu-feedstock/issues/121
- [x] Patch out GCC version check https://github.com/conda-forge/pytorch_scatter-feedstock/pull/46/commits/d3096d1ad891f11363f8af4c0ebf7eeff2b8f0ea  https://github.com/conda-forge/pytorch_scatter-feedstock/pull/46
- [x] use `libcblas` https://github.com/conda-forge/pytorch-cpu-feedstock/pull/123#discussion_r923335983

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by conda-forge-linter** [comment]
Hi! This is the friendly automated conda-forge-webservice.

I just wanted to let you know that I rerendered the recipe in conda-forge/pytorch-cpu-feedstock#127.

**Comment by hmaarrfk** [comment]
Closing this as we already have an other issue tracking the remaining point.
