### ISSUE TITLE
Large Windows Runners

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pytorch-cpu-feedstock#268]
### This fundable has not been submitted yet.

- [X] This fundable has not been submitted yet.

### Motivation

Infrastructure needed to help package large windows packages. 

### Expected result

A certain amount of large runners that can "opt in". Runners must not be exclusive to any one package, but rather for use by the conda-forge community as a whole.

### Work items

- [ ] Draft a sample donation policy.
- [ ] Draft a sample set of requirements for the machine.
- [ ] Do we need a visual studio license?
- [ ] Execute on the donation of pool of windows runners.

### References

- [ ] The donation of large GPU runners.

### Skills / personnel

Infrastructure setup for Windows runners.

### Estimated costs and/or resources needed (optional)

I've been building cuda packages quickly on 128 GB of RAM. This can probably be setup for approximately $2k USD per machine.

We would probably need something like 10 large machines.

So about $20k of donated hardware + 10% FTE for maintenance?

**Comment by h-vetinari** [comment]
Isn't prefix planning already on donate some runners for this purpose in #231

**Comment by hmaarrfk** [comment]
I'm leaving this here open as a way for people to put money and work where their intentions are.

**Comment by hmaarrfk** [comment]
For these funded projects, we need a proposal, a SOW, a budget, and a maintenance plance. Even writing this would be greatly helpful!

**Comment by ericdill** [comment]
@hmaarrfk do you have more info on the machine specs you're looking for? also is the $2k/20k a price per month or price per year?

**Comment by hmaarrfk** [comment]
My pricing was more on "home built" infrastructure. 

We would need a place to store these machines, and a way to cool them. 

But I'm fairly certain you can do it in an Asus (Intel) NUC with like 96GB of RAM. 

So a 1 time purchase of about 20k for hardware infra, and then some software engineer to setup and maintain (not sure how things are costed for the GPU runners).

Should last like 4 years. 

These are just "performant" machines, no GPUs. (i7 processor with lots of RAM).

**Comment by jaimergp** [comment]
xref to our "lessons learned" blog post: https://quansight.com/post/building-a-gpu-ci-service-for-conda-forge/. Might be useful while deciding how to do this. 

For Windows, licensing might be something else to consider if they are publicly available machines.

**Comment by hmaarrfk** [comment]
The windows licensing is important.

I'm going off:
![Image](https://github.com/user-attachments/assets/472bb8fa-a821-4ca8-94ed-87b10774b6b5)

So hopefully that is OK! There might be more to the story too. But it is a consideration!

**Comment by jakirkham** [comment]
Cross-linking the `.cirun` PR adding Windows CI for the PyTorch feedstock: https://github.com/conda-forge/.cirun/pull/14

**Comment by Tobias-Fischer** [comment]
I guess we can close here @hmaarrfk?

**Comment by hmaarrfk** [comment]
I'm not sure. 

Let's see how the runners work over the next 6 months

**Comment by hmaarrfk** [comment]
Perhaps we can now move this to a call to action to just provide any kind of funding:
https://numfocus.org/donate-to-conda-forge
